name: "Close stale issues"
on:
  schedule:
    - cron: "0 0 * * *"
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: >
            This issue is stale because it has been open for 14 days with
            no activity. If no action is taken it will be closed in 7 days.
          days-before-stale: 14
          days-before-close: 7
          exempt-issue-labels: triaged
