name: lint
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - "*"
jobs:
  build:
    runs-on: macos-10.15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Print versions
        run: |
          bash -c 'echo $BASH_VERSION'
          brew --version
          make --version
      - name: Homebrew install linter
        run: brew bundle
      - name: Run lint checks
        run: make lint
