name: "Create release"
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '*.*.*'  # Push events to matching `*.*.*`, i.e. `0.6.8`, `20.15.10`
jobs:
  release:
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create release assets
        run: |
          echo "Install packages"
          brew bundle
          echo "Update path"
          export PATH="/usr/local/opt/coreutils/libexec/gnubin:/usr/local/bin:/usr/local/sbin:${PATH}"
          echo "Create EFI folder"
          make run
          echo "Create tarball for ${GITHUB_REF}"
          RELEASE="${GITHUB_REF##*/}"
          echo "RELEASE=${RELEASE}" >> $GITHUB_ENV
          echo "Release name: ${RELEASE}"
          tar -zcvf EFI-OC-${RELEASE}-ASUS-ROG-MAXIMUS-XI-HERO.tar.gz EFI
          echo "Create zip"
          zip EFI-OC-${RELEASE}-ASUS-ROG-MAXIMUS-XI-HERO.zip -r EFI
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: OpenCore ${{ env.RELEASE }} support
          draft: false
          prerelease: false
          files: |
            EFI-OC-${{ env.RELEASE }}-ASUS-ROG-MAXIMUS-XI-HERO.tar.gz
            EFI-OC-${{ env.RELEASE }}-ASUS-ROG-MAXIMUS-XI-HERO.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
